## Dependecies

In [1]:
import pandas as pd
from sqlalchemy import create_engine

## Store CSV into DataFrame

In [6]:
sniiv_file = "../Resources/sniiv.csv"
sniiv_df = pd.read_csv(sniiv_file, encoding='latin-1')
sniiv_df.head()

,Año,Mes acumulado,Clave Entidad INEGI,Entidad Federativa,Clave Municipio INEGI,Municipio,Modalidad,Genero,Rango de Edad,Rango de Ingresos UMA,Valor de la Vivienda,Acciones,Monto
0,2020,12,15,México,31,Chimalhuacán,Mejoramientos,Hombre,60 o más,2.61 a 4.00,Económica,7,"287,400.24"
1,2020,12,15,México,31,Chimalhuacán,Mejoramientos,Hombre,30 a 59,2.61 a 4.00,Económica,23,"930,547.12"
2,2020,12,15,México,31,Chimalhuacán,Mejoramientos,Hombre,29 o menos,2.61 a 4.00,Económica,10,"341,732.00"
3,2020,12,15,México,31,Chimalhuacán,Mejoramientos,Hombre,60 o más,2.6 o menos,Económica,3,"126,613.52"
4,2020,12,15,México,31,Chimalhuacán,Mejoramientos,Hombre,30 a 59,2.6 o menos,Económica,9,"343,699.68"

In [7]:
inegi_file = "../Resources/inegi.csv"
inegi_df = pd.read_csv(inegi_file)
inegi_df.head()

C:\Users\Juan Cortez\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (8) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,ENTIDAD,NOM_ENT,MUN,NOM_MUN,LOC,NOM_LOC,LONGITUD,LATITUD,ALTITUD,POBTOT,...,VPH_CEL,VPH_INTER,VPH_STVP,VPH_SPMVPI,VPH_CVJ,VPH_SINRTV,VPH_SINLTC,VPH_SINCINT,VPH_SINTIC,TAMLOC
0,0,Total nacional,0,Total nacional,0,Total nacional,NaN,NaN,NaN,126014024,...,30775898,18307193,15211306,6616141,4047100,1788552,3170894,15108204,852871,*
1,0,Total nacional,0,Total nacional,9998,Localidades de una vivienda,NaN,NaN,NaN,250354,...,47005,8385,18981,1732,1113,12775,14143,51293,7154,*
2,0,Total nacional,0,Total nacional,9999,Localidades de dos viviendas,NaN,NaN,NaN,147125,...,25581,5027,11306,971,708,8247,10065,29741,5283,*
3,1,Aguascalientes,0,Total de la entidad Aguascalientes,0,Total de la Entidad,NaN,NaN,NaN,1425607,...,359895,236003,174089,98724,70126,6021,15323,128996,1711,*
4,1,Aguascalientes,0,Total de la entidad Aguascalientes,9998,Localidades de una vivienda,NaN,NaN,NaN,3697,...,732,205,212,48,41,39,62,530,20,*